# Generated by Django 5.0.6 on 2024-10-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usuario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='sin nombre', max_length=128),
            preserve_default=False,
        ),
    ]
